### ISSUE TITLE
Example yaml Datasets are null

### ISSUE THREAD

**Issue by gracetian6** [uvm-plaid/chorus#6]
I ran the example described in the README.md:
 `mvn exec:java -Dexec.mainClass="examples.MechanismExamples"`

However, the datasets have no values, and it isn't clear how to add values to the datasets.  I know that the empty dataset is stored in [`src/test/resources/schema.yaml`](https://github.com/uvm-plaid/chorus/blob/master/src/test/resources/schema.yaml)  with column names, but I have no idea how to add entries to it. **Is it possible to add values to this test dataset?** And is it possible to convert CSV values to yaml? (I couldn't find any google articles on this.)

This would help me run my own DP programs.

**Comment by jnear** [comment]
The YAML files configure the *schema* of the underlying data, and don't encode the data itself. It's not possible to use the YAML config files to store your data.

To access data, Chorus needs to be connected to a SQL database containing the data. The `execute` function that actually runs a query on the data is defined [here](https://github.com/uvm-plaid/chorus/blob/master/src/main/scala/chorus/util/DB.scala#L15), and its definition shows what system properties you need to set in order to hook up your own database. By default, Chorus uses a "dummy database" (defined in that file) which always returns a single row with a single "1" value in it (no matter what the query is).
